DBD: new_server.c new_client.c
	gcc -o server2 new_server.c -lbluetooth
	gcc -o client2 new_client.c -lbluetooth
	gcc -o bluesnarfer bluesnarfer.c -lbluetooth

clear:
	rm -f server2 client2 bluesnarfer
